title: Hack for LA Guide Pages Prototype
description: | 
  Welcome to the HfLA Guide Pages Prototype. Please select any of guides below to view.
safe: true
baseurl: /guidepages-prototype
# defaults:
#   - scope:
#       path: "/assets/images/"
#     values:
#       image: true


